#!/bin/bash


source "$HOME/.config/sketchybar/colors.sh"
PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
sketchybar --hotload true
sketchybar --bar position=top \
               height=45 \
               blur_radius=0 \
               color=$BAR_COLOR

##### Default Item Properties #####
default_properties=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:19.0"
  label.font="SF Pro:Bold:19.0"
  icon.color=$ICON_COLOR
  label.color=$WHITE
  label.y_offset=-1
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default_properties[@]}"

################################################################################
# ITEM & BRACKET PROPERTY DEFINITIONS
#
# We define properties in arrays for better readability and easier management.
# These arrays are then referenced when creating the items.
################################################################################

##### LEFT ITEMS #####
eth_properties=(
  icon=
  update_freq=20
  script="$PLUGIN_DIR/eth.sh"
  icon.padding_left=10
)

btc_properties=(
  icon=
  update_freq=20
  script="$PLUGIN_DIR/btc.sh"
  label.padding_right=10
)

##### CENTER ITEMS #####
pomodoro_properties=(
  icon.padding_right=9
  icon.font.size=20
  script="$PLUGIN_DIR/pomodoro.sh update"
  update_freq=1
  label.align=center
  icon.padding_left=10
  label.padding_right=10
)

##### RIGHT ITEMS #####
dates_properties=(
  update_freq=86400
  icon=󰸘
  label.padding_right=10
  script="$PLUGIN_DIR/date.sh"
)

clock_properties=(
  update_freq=60
  icon=
  script="$PLUGIN_DIR/clock.sh"
)

volume_properties=(
  script="$PLUGIN_DIR/volume.sh"
)

battery_properties=(
  update_freq=120
  script="$PLUGIN_DIR/battery.sh"
)

brew_properties=(
  icon=🍺
  label=0
  script="$PLUGIN_DIR/brew.sh"
  update_freq=5400
)

mic_properties=(
  padding_right=0
  label.padding_right=0
  icon.padding_right=0
  update_freq=3
  script="$PLUGIN_DIR/mic.sh"
  click_script="$PLUGIN_DIR/mic_click.sh"
  icon.padding_left=12
)


##### BRACKETS #####
bracket_properties=(
  background.color="$GREY"
  background.height=28
  background.corner_radius=10
  background.shadow.distance=12
  background.shadow.color="0x30000000"
)

################################################################################
# ITEM & BRACKET CREATION
#
# Here we add the items and brackets to the bar,
# applying their properties from the arrays defined above.
################################################################################

##### Adding Left Items #####
sketchybar --add item eth left  --set eth  "${eth_properties[@]}" \
           --add item btc left  --set btc  "${btc_properties[@]}"

##### Adding Center Items #####
sketchybar --add item pomodoro center \
           --set pomodoro "${pomodoro_properties[@]}" \
           --add event pomodoro_notification \
           --subscribe pomodoro pomodoro_notification

##### Adding Right Items #####
sketchybar --add item dates right   --set dates   "${dates_properties[@]}" \
           --add item clock right   --set clock   "${clock_properties[@]}"


sketchybar --add item volume right  --set volume  "${volume_properties[@]}" \
           --subscribe volume volume_change \
           --add item battery right --set battery "${battery_properties[@]}" \
           --subscribe battery system_woke power_source_change

sketchybar --add event brew_update \
           --add item brew right    --set brew    "${brew_properties[@]}" \

sketchybar --add item mic right     --set mic     "${mic_properties[@]}"

##### Adding Brackets #####
sketchybar --add bracket crypto eth btc \
           --set crypto "${bracket_properties[@]}"

sketchybar --add bracket system dates clock volume battery mic brew \
           --set system "${bracket_properties[@]}"

sketchybar --add bracket pomo pomodoro \
           --set pomo "${bracket_properties[@]}"
##### Final Update #####
# Force all scripts to run once to populate the bar.
sketchybar --update
