#!/bin/bash


source "$HOME/.config/sketchybar/colors.sh"
PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
sketchybar --hotload true
sketchybar --bar position=top \
               height=40 \
               blur_radius=0 \
               color=$BAR_COLOR

##### Default Item Properties #####
default_properties=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:18.0"
  label.font="Hack Nerd Font:Bold"
  icon.color=$ICON_COLOR
  label.color=$WHITE
  label.font.size=18.0
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default_properties[@]}"

################################################################################
# ITEM & BRACKET PROPERTY DEFINITIONS
#
# We define properties in arrays for better readability and easier management.
# These arrays are then referenced when creating the items.
################################################################################

##### LEFT ITEMS #####
eth_properties=(
  icon=
  update_freq=20
  script="$PLUGIN_DIR/eth.sh"
)

btc_properties=(
  icon=
  update_freq=20
  script="$PLUGIN_DIR/btc.sh"
)

##### CENTER ITEMS #####
pomodoro_properties=(
  padding_left=10
  icon.padding_left=2
  icon.font.size=20
  script="$PLUGIN_DIR/pomodoro.sh update"
  update_freq=1
  label.align=center
)

##### RIGHT ITEMS #####
dates_properties=(
  update_freq=86400
  icon=󰸘
  label.padding_right=10
  script="$PLUGIN_DIR/date.sh"
)

clock_properties=(
  update_freq=10
  icon=
  script="$PLUGIN_DIR/clock.sh"
)

volume_properties=(
  script="$PLUGIN_DIR/volume.sh"
)

battery_properties=(
  update_freq=120
  script="$PLUGIN_DIR/battery.sh"
)

brew_properties=(
  icon=
  label=?
  padding_right=10
  script="$PLUGIN_DIR/brew.sh"
)

mic_properties=(
  update_freq=3
  script="$PLUGIN_DIR/mic.sh"
  click_script="$PLUGIN_DIR/mic_click.sh"
  padding_right=0
  padding_left=10
)

spacer_properties=(
  width=10
)

##### BRACKETS #####
bracket_properties=(
  background.color="$GREY"
  background.height=28
  background.corner_radius=12
)

################################################################################
# ITEM & BRACKET CREATION
#
# Here we add the items and brackets to the bar,
# applying their properties from the arrays defined above.
################################################################################

##### Adding Left Items #####
sketchybar --add item eth left  --set eth  "${eth_properties[@]}" \
           --add item btc left  --set btc  "${btc_properties[@]}"

##### Adding Center Items #####
sketchybar --add item pomodoro center \
           --set pomodoro "${pomodoro_properties[@]}" \
           --add event pomodoro_notification \
           --subscribe pomodoro pomodoro_notification

##### Adding Right Items #####
sketchybar --add item dates right   --set dates   "${dates_properties[@]}" \
           --add item clock right   --set clock   "${clock_properties[@]}"

sketchybar --add item spacer_2 right --set spacer_2 "${spacer_properties[@]}"

sketchybar --add item volume right  --set volume  "${volume_properties[@]}" \
           --subscribe volume volume_change \
           --add item battery right --set battery "${battery_properties[@]}" \
           --subscribe battery system_woke power_source_change

sketchybar --add event brew_update \
           --add item brew right    --set brew    "${brew_properties[@]}" \
           --subscribe brew brew_update

sketchybar --add item mic right     --set mic     "${mic_properties[@]}"

##### Adding Brackets #####
sketchybar --add bracket crypto eth btc \
           --set crypto "${bracket_properties[@]}"

sketchybar --add bracket time dates clock \
           --set time "${bracket_properties[@]}"

sketchybar --add bracket utils volume battery mic brew \
           --set utils "${bracket_properties[@]}"


##### Final Update #####
# Force all scripts to run once to populate the bar.
sketchybar --update

echo "SketchyBar configuration loaded!"
